### ISSUE TITLE
FYI: Embulk 0.10.x and homepage URL.

### ISSUE THREAD

**Issue by hiroyuki-sato** [datable-inc/embulk-output-cdata#8]
Hello, developer.

Thank you for developing the Embulk plugin. Just for your information.

### 1. Embulk 0.10.x

You may need to catch up with Embulk 0.10.x. Please read this document.

https://dev.embulk.org/topics/get-ready-for-v0.11-and-v1.0.html
https://zenn.dev/dmikurube/articles/get-ready-for-embulk-v0-11-and-v1-0 (Japanese)

### 2. spec homepage.

This configuration may help plugin users.
https://github.com/datable-inc/embulk-output-cdata/blob/95da279b63d640948c1b3189b6551f19cbe6418f/build.gradle#L88

Ex. This URL used home page links in RubyGems.
https://rubygems.org/gems/embulk-parser-jsonpath

Best regards

**Comment by sampo02** [comment]
@hiroyuki-sato 
Thank you for your information.
I will catch up the documentation and update spec homepage.

Thank you,

**Comment by hiroyuki-sato** [comment]
@sampo02 Thank you for your comment.
Please let me know if you have any questions. [Twitter](https://twitter.com/hiroysato) or mention me on this thread.
